site_name: PSimulator
theme : readthedocs 
extra_css:
  - css/extra.css
nav :
  - Acceuil : index.md
  - Hiérarchie : hierarchy.md
  - GameObjects : 
    - PlacementManager : gameobjects/PlacementManager.md
    - WireManager : gameobjects/WireManager.md
  - Scritps : 
    - Introduction: scripts/index.md  
    - PlacementManager : scripts/PlacementManager.md
    - WireManager : scripts/WireManager.md
  - Fonctionnalités :  
    - Introduction: functionalities/index.md
    - Spawning: functionalities/spawning.md
    - Selection: functionalities/selection.md
    - Drag & Drop: functionalities/drag_and_drop.md
  - Guides : 
    - Guide de Contribution: contribution.md 